(()=>{
const MEDIA_LIBRARY_BACKGROUND_CATEGORIES=Object.freeze([
  ['Doporučené','landscape'],['Příroda','nature landscape'],['Hory','mountain landscape'],['Les','forest landscape'],['Moře','coast landscape'],['Jezera','lake landscape'],['Vodopády','waterfall landscape'],['Obloha','clouds sky landscape'],['Květiny','flower field landscape'],['Vesmír','nebula galaxy'],['Města','city skyline'],['Architektura','architecture exterior'],['Noční','night landscape'],['Jaro','spring landscape'],['Léto','summer landscape'],['Podzim','autumn landscape'],['Zima','winter landscape'],['Česká republika','Czech landscape'],['Evropa','European landscape'],['Abstraktní','abstract colorful background']
]);
const MEDIA_LIBRARY_GENERAL_CATEGORIES=Object.freeze([
  ['Příroda','nature landscape'],['Zvířata','animals wildlife'],['Vesmír','space astronomy'],['Geografie','world geography landscape'],
  ['Historie','history historical photograph'],['Umění','famous art painting'],['Architektura','architecture building'],['Věda','science laboratory'],
  ['Roční období','seasons landscape'],['Škola','school education classroom'],['Jídlo','food cuisine'],['Sport','sport athletics'],
  ['Města','city skyline'],['Česká republika','Czech Republic landscape'],['Evropa','Europe landmarks'],['Mapy','world map'],
  ['Technologie','technology computer'],['Hudba','musical instruments'],['Doprava','transport vehicles'],['Textury','abstract texture background'],
]);
const MEDIA_LIBRARY_BACKGROUND_BAD_TITLE=/\b(portrait|headshot|selfie|stamp|postage|coin|banknote|television|tv set|logo|coat of arms|emblem|seal|scan|screenshot|icon|passport|document|diagram|poster|book cover|flag|medal|ticket|label|plaque|certificate|person|people|woman|women|man|men|boy|girl|actor|actress|politician|president|footballer|player|singer)\b/i;
const MEDIA_LIBRARY_BACKGROUND_GOOD_TITLE=/\b(landscape|panorama|panoramic|sunset|sunrise|skyline|mountain|forest|ocean|coast|beach|lake|river|waterfall|valley|desert|aurora|nebula|galaxy|architecture|cityscape|night|blue hour|texture|abstract|scenic|nature)\b/i;
const MEDIA_LIBRARY_BACKGROUND_FALLBACKS=Object.freeze({'nature landscape':'scenic nature','mountain landscape':'mountains panorama','forest landscape':'forest scenery','coast landscape':'sea coast','lake landscape':'lake panorama','waterfall landscape':'waterfall nature','clouds sky landscape':'sky clouds','flower field landscape':'flowers meadow','nebula galaxy':'astronomy nebula','city skyline':'cityscape panorama','architecture exterior':'architecture building exterior','night landscape':'night scenery','spring landscape':'spring nature','summer landscape':'summer nature','autumn landscape':'autumn forest','winter landscape':'winter snow landscape','Czech landscape':'Czech Republic nature','European landscape':'Europe scenery','abstract colorful background':'abstract texture'});
function mediaLibraryBackgroundFallbackQuery(query){return MEDIA_LIBRARY_BACKGROUND_FALLBACKS[String(query||'')]||'nature landscape'}
let mediaLibraryRequestId=0;

function mediaLibraryDialog(){return $('#mediaLibraryDialog')}
function mediaLibraryPlainText(value){const text=String(value||'');if(!text.includes('<'))return text.replace(/\s+/g,' ').trim();try{return(new DOMParser().parseFromString(text,'text/html').body.textContent||'').replace(/\s+/g,' ').trim()}catch(_){return text.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()}}
function mediaLibrarySafeImage(page){const info=page?.imageinfo?.[0]||{},url=sanitizeLessonImageUrl(info.thumburl||info.url);if(!url)return null;const meta=info.extmetadata||{},width=Math.max(0,Number(info.width)||0),height=Math.max(0,Number(info.height)||0);return{id:String(page.pageid||page.title||url),url,sourcePage:sanitizeLessonSourceUrl(page.fullurl||`https://commons.wikimedia.org/wiki/${encodeURIComponent(String(page.title||'').replace(/ /g,'_'))}`),sourceLabel:String(page.title||'Wikimedia Commons').replace(/^File:/i,'').slice(0,160),license:mediaLibraryPlainText(meta.LicenseShortName?.value||meta.UsageTerms?.value||'Wikimedia Commons').slice(0,80),author:mediaLibraryPlainText(meta.Artist?.value||meta.Credit?.value||'').slice(0,120),description:mediaLibraryPlainText(meta.ImageDescription?.value||meta.ObjectName?.value||'').slice(0,300),assessment:mediaLibraryPlainText(meta.Assessments?.value||'').slice(0,120),width,height,aspect:width&&height?width/height:0}}
function mediaLibraryBackgroundScore(item){const aspect=Number(item?.aspect)||0,title=String(item?.sourceLabel||''),searchText=`${title} ${item?.description||''}`;let score=0;if(MEDIA_LIBRARY_BACKGROUND_BAD_TITLE.test(searchText))score-=180;if(MEDIA_LIBRARY_BACKGROUND_GOOD_TITLE.test(searchText))score+=40;if(/featured|quality|valued/i.test(String(item?.assessment||'')))score+=30;if(item.width>=1920)score+=25;else if(item.width>=1280)score+=16;else if(item.width>=900)score+=7;if(item.height>=900)score+=12;else if(item.height>=650)score+=7;if(aspect>=1.45&&aspect<=2.15)score+=45-Math.abs(aspect-(16/9))*28;else if(aspect>=1.2&&aspect<=2.7)score+=12;else score-=80;return score}
function mediaLibraryBackgroundItems(items){const unique=[...new Map(items.map(item=>[item.url,item])).values()],ranked=unique.map(item=>({item,score:mediaLibraryBackgroundScore(item)})).sort((a,b)=>b.score-a.score);let selected=ranked.filter(entry=>entry.score>=-20&&(!entry.item.aspect||entry.item.aspect>=1.15)).map(entry=>entry.item);if(selected.length<12)selected=ranked.filter(entry=>!MEDIA_LIBRARY_BACKGROUND_BAD_TITLE.test(`${entry.item.sourceLabel} ${entry.item.description||''}`)&&(!entry.item.aspect||entry.item.aspect>=1.05)).map(entry=>entry.item);return selected}
function mediaLibraryButton(label,datasetKey,datasetValue,className=''){const button=document.createElement('button');button.type='button';button.textContent=label;if(className)button.className=className;button.dataset[datasetKey]=datasetValue;return button}
function mediaLibraryRenderCategories(){const root=$('#mediaLibraryCategories');if(!root)return;root.replaceChildren();const backgroundMode=App.ui.mediaLibraryTarget?.kind==='background',categories=backgroundMode?MEDIA_LIBRARY_BACKGROUND_CATEGORIES:MEDIA_LIBRARY_GENERAL_CATEGORIES;for(const[label,query]of categories)root.append(mediaLibraryButton(label,'mediaQuery',query))}
function mediaLibraryRenderPresets(){const root=$('#mediaLibraryPresets');if(!root)return;root.replaceChildren();for(const bg of LESSON_BACKGROUND_PRESETS){const button=mediaLibraryButton('','mediaPreset',`${bg.type}:${bg.value}`,`media-preset board-bg-${bg.type}-${bg.value}`);button.title=bg.name;const span=document.createElement('span');span.textContent=bg.name;button.append(span);root.append(button)}}
function mediaLibraryRenderStatus(text,{error=false}={}){const root=$('#mediaLibraryResults');if(!root)return;const status=document.createElement('div');status.className=`media-library-status${error?' error':''}`;status.textContent=String(text||'');root.replaceChildren(status)}
function mediaLibraryCard(item,index){const button=mediaLibraryButton('','mediaResult',String(index),'media-card');const image=document.createElement('img');image.src=item.url;image.alt=item.sourceLabel;image.loading='lazy';image.referrerPolicy='no-referrer';image.addEventListener('error',()=>{button.classList.add('image-error');image.alt='Náhled se nepodařilo načíst.'},{once:true});const text=document.createElement('span'),title=document.createElement('b'),meta=document.createElement('small');title.textContent=item.sourceLabel;const size=item.width&&item.height?`${item.width}×${item.height}`:'';meta.textContent=[size,item.author,item.license].filter(Boolean).join(' · ');text.append(title,meta);button.append(image,text);return button}
function mediaLibraryRenderResults(items,{append=false}={}){const root=$('#mediaLibraryResults');if(!root)return;const previous=append?(App.ui.mediaLibraryResults||[]):[];App.ui.mediaLibraryResults=[...previous,...items];if(!App.ui.mediaLibraryResults.length){mediaLibraryRenderStatus(App.ui.mediaLibraryTarget?.kind==='background'?'Pro tento výraz jsem nenašel vhodné široké pozadí. Zkuste jinou kategorii nebo hledání.':'Pro tento výraz jsem nenašel vhodné obrázky. Zkuste jiné slovo.');return}const fragment=document.createDocumentFragment();App.ui.mediaLibraryResults.forEach((item,index)=>fragment.append(mediaLibraryCard(item,index)));if(App.ui.mediaLibraryContinue!==null&&App.ui.mediaLibraryContinue!==undefined){const more=mediaLibraryButton('Načíst dalších 50 obrázků','mediaMore','1','media-load-more');fragment.append(more)}root.replaceChildren(fragment)}
async function mediaLibraryFetchPage(clean,offset=null){const args={action:'query',format:'json',formatversion:'2',generator:'search',gsrsearch:`${clean} filetype:bitmap`,gsrnamespace:'6',gsrlimit:'50',prop:'imageinfo|info',iiprop:'url|size|mime|mediatype|extmetadata',iiurlwidth:'1920',inprop:'url',origin:'*'};if(offset!==null&&offset!==undefined)args.gsroffset=String(offset);const params=new URLSearchParams(args),response=await fetch(`https://commons.wikimedia.org/w/api.php?${params.toString()}`,{method:'GET',credentials:'omit',referrerPolicy:'no-referrer',headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`Commons ${response.status}`);const json=await response.json();return{raw:(json?.query?.pages||[]).map(mediaLibrarySafeImage).filter(Boolean),next:json?.continue?.gsroffset??null}}
async function mediaLibrarySearch(query,{append=false}={}){const clean=String(query||'').trim().slice(0,120);if(!clean)return;const requestId=++mediaLibraryRequestId,background=App.ui.mediaLibraryTarget?.kind==='background';if(!append){App.ui.mediaLibraryResults=[];App.ui.mediaLibraryContinue=null;App.ui.mediaLibraryQuery=clean;mediaLibraryRenderStatus('Načítám výběr obrázků z Wikimedia Commons…')}App.ui.mediaLibraryBusy=true;try{let offset=append?App.ui.mediaLibraryContinue:null,raw=[],next=offset;const maxPages=background&&!append?3:1;for(let page=0;page<maxPages;page++){const result=await mediaLibraryFetchPage(clean,next);if(requestId!==mediaLibraryRequestId)return;raw.push(...result.raw);next=result.next;if(!background||mediaLibraryBackgroundItems(raw).length>=24||next===null)break}let items=background?mediaLibraryBackgroundItems(raw).slice(0,50):raw;if(background&&!append&&items.length<12){const fallback=mediaLibraryBackgroundFallbackQuery(clean);if(fallback!==clean){const extra=await mediaLibraryFetchPage(fallback,null);if(requestId!==mediaLibraryRequestId)return;raw.push(...extra.raw);items=mediaLibraryBackgroundItems(raw).slice(0,50);if(items.length)next=null}}App.ui.mediaLibraryContinue=next;mediaLibraryRenderResults(items,{append})}catch(error){if(requestId!==mediaLibraryRequestId)return;captureError(error,'media-library');if(append){toast('Další obrázky se nepodařilo načíst.','error')}else mediaLibraryRenderStatus(navigator.onLine===false?'Knihovna obrázků vyžaduje připojení k internetu.':'Knihovnu Wikimedia Commons se nepodařilo načíst. Zkuste hledání zopakovat.',{error:true})}finally{if(requestId===mediaLibraryRequestId)App.ui.mediaLibraryBusy=false}}
function openMediaLibrary(target='background',widgetId=''){const dialog=mediaLibraryDialog();if(!dialog){toast('Knihovna obrázků není dostupná.','error');return}App.ui.mediaLibraryTarget={kind:target,widgetId:String(widgetId||'')};App.ui.mediaLibraryResults=[];App.ui.mediaLibraryContinue=null;mediaLibraryRenderCategories();mediaLibraryRenderPresets();const presets=$('#mediaLibraryPresetSection');if(presets)presets.hidden=target!=='background';const title=$('#mediaLibraryTitle');if(title)title.textContent=target==='background'?'Knihovna pozadí':'Knihovna obrázků';const input=$('#mediaLibrarySearch'),defaultQuery=target==='background'?'landscape':'nature landscape';if(input)input.value=defaultQuery;if(!dialog.open)dialog.showModal();requestAnimationFrame(()=>input?.focus());void mediaLibrarySearch(defaultQuery)}
function closeMediaLibrary(){const dialog=mediaLibraryDialog();if(dialog?.open)dialog.close();App.ui.mediaLibraryTarget=null}
function mediaLibraryChoose(item){if(!item)return;const target=App.ui.mediaLibraryTarget||{kind:'background'};if(target.kind==='background'){lessonBoardScene().background={type:'image',url:item.url,sourcePage:item.sourcePage,sourceLabel:item.sourceLabel,license:item.license};closeMediaLibrary();lessonBoardPersist('lesson_background_image');toast('Obrázek byl nastaven jako pozadí plochy.','success');return}if(target.kind==='replace-widget'){const widget=lessonBoardWidget(target.widgetId);if(widget&&widget.type==='image')widget.data={...widget.data,url:item.url,sourcePage:item.sourcePage,sourceLabel:item.sourceLabel,license:item.license};closeMediaLibrary();lessonBoardPersist('lesson_image_replace');toast('Obrázek byl změněn.','success');return}closeMediaLibrary();lessonBoardAddImageWidget(item);toast('Obrázek byl přidán na pracovní plochu.','success')}
function bindMediaLibrary(){document.addEventListener('submit',event=>{if(!event.target.matches('#mediaLibraryForm'))return;event.preventDefault();void mediaLibrarySearch($('#mediaLibrarySearch')?.value)});document.addEventListener('click',event=>{const query=event.target.closest('[data-media-query]');if(query){const input=$('#mediaLibrarySearch');if(input)input.value=query.dataset.mediaQuery;void mediaLibrarySearch(query.dataset.mediaQuery);return}const more=event.target.closest('[data-media-more]');if(more&&!App.ui.mediaLibraryBusy){void mediaLibrarySearch(App.ui.mediaLibraryQuery||$('#mediaLibrarySearch')?.value,{append:true});return}const result=event.target.closest('[data-media-result]');if(result){mediaLibraryChoose(App.ui.mediaLibraryResults?.[Number(result.dataset.mediaResult)]);return}const preset=event.target.closest('[data-media-preset]');if(preset){const[type,value]=preset.dataset.mediaPreset.split(':');lessonBoardScene().background={type,value};closeMediaLibrary();lessonBoardPersist('lesson_background_preset');toast('Pozadí pracovní plochy bylo změněno.','success');return}if(event.target.closest('[data-media-close]'))closeMediaLibrary()})}

let mediaLibraryBound=false;
const originalBindMediaLibrary=bindMediaLibrary;
bindMediaLibrary=function(){if(mediaLibraryBound)return;mediaLibraryBound=true;return originalBindMediaLibrary()};
globalThis.__SORTIO_MEDIA_LIBRARY__={open:openMediaLibrary,bind:bindMediaLibrary};
})();
