(()=>{
const DEMO_STUDENTS=[['Anna','Nováková'],['Adam','Svoboda'],['Barbora','Dvořáková'],['Cyril','Procházka'],['Daniela','Černá'],['David','Kučera'],['Eliška','Veselá'],['Filip','Horák'],['Gabriela','Němcová'],['Hynek','Marek'],['Ivana','Pokorná'],['Jakub','Král'],['Karolína','Benešová'],['Lukáš','Fiala'],['Marie','Sedláčková'],['Matěj','Růžička'],['Nela','Hájková'],['Ondřej','Jelínek'],['Petra','Konečná'],['Radek','Urban'],['Sára','Bláhová'],['Tomáš','Navrátil'],['Viktorie','Malá'],['Zdeněk','Kříž']];
function createDemoClass(){const existing=App.data.classes.find(item=>item.demo&&!item.archived);if(existing){setSelectedClass(existing.id);toast('Ukázková třída už je připravena.','info');return existing}const students=DEMO_STUDENTS.map(([first,last],index)=>sanitizeStudent({id:uid('demo-student'),firstName:first,lastName:last,present:index!==7,groupLevel:['A','B','C'][index%3],frontPreference:index===2||index===11,soloPreference:index===4,pairingSex:index%2===0?'girl':'boy',createdAt:nowIso(),updatedAt:nowIso()}));const item=createClass({name:'Ukázková třída 2.A',schoolYear:'2026/2027',students});item.demo=true;item.topicCatalog=['Obnovitelné zdroje','Městská doprava','Umělá inteligence','Ochrana vody','Mediální gramotnost','Budoucnost školy'];item.groupRules.apart=[[students[0].id,students[1].id]];item.groupRules.together=[[students[4].id,students[5].id]];saveData({event:'demo_class_create'});toast('Anonymní ukázková třída byla vytvořena.','success');return item}
function productionCheck(id,label,fn){const start=performance.now();try{const value=fn();return Promise.resolve(value).then(detail=>({id,label,state:'pass',detail:String(detail||'Prošlo.'),durationMs:Math.round((performance.now()-start)*10)/10})).catch(error=>({id,label,state:'fail',detail:error.message,durationMs:Math.round((performance.now()-start)*10)/10}))}catch(error){return Promise.resolve({id,label,state:'fail',detail:error.message,durationMs:Math.round((performance.now()-start)*10)/10})}}
function productionCheckDefinitions(){return[
  ['storage','Lokální úložiště',()=>{const storage=safeStorage();if(!storage)throw new Error('Úložiště není dostupné.');storage.setItem('__sortio_prod_test__','ok');if(storage.getItem('__sortio_prod_test__')!=='ok')throw new Error('Zápis a čtení selhalo.');storage.removeItem('__sortio_prod_test__');return'Zápis a čtení funguje.'}],
  ['schema','Datový model v5',()=>App.data?.schema==='sortio-data-v5'&&App.data?.version===5?'Schéma v5 je aktivní.':Promise.reject(new Error('Schéma v5 není aktivní.'))],
  ['backup','Záloha a kontrolní součet',()=>{const payload=buildBackupPayload();validateBackupPayload(payload);return`Ověřeno ${payload.summary.classes} tříd a ${payload.summary.students} studentů.`}],
  ['import','Import z IS',()=>{const parsed=parseImport('anna.novakova@example.com; petr.svoboda@example.com, anna.novakova@example.com');if(parsed.rows.length!==2||parsed.invalid.length!==1)throw new Error('Parser nevrátil očekávaný výsledek.');return'Oddělovače a duplicity jsou správně rozpoznány.'}],
  ['groups','Výkon skupin pro 120 studentů',()=>{const students=Array.from({length:120},(_,index)=>sanitizeStudent({id:`perf-${index}`,firstName:`Student${index+1}`,lastName:'Testovací',groupLevel:['A','B','C'][index%3]}));const mock={students,groupRules:{together:[],apart:[],pins:{}},groupHistory:[]};const groups=solveSmartPartition(mock,students,groupLengths(students.length,{mode:'size',value:4}),'balanced');if(groups.length!==30||groups.some(group=>group.studentIds.length!==4))throw new Error('Rozdělení 120 studentů není správné.');return'120 studentů bylo rozděleno do 30 skupin.'}],
  ['seating','Geometrie učebny',()=>{const rows=createSeatLayout('rows',10,12),pairs=createSeatLayout('pairs',5,6),u=createSeatLayout('u',6,8);if(rows.length!==120||pairs.length!==60||u.length!==18)throw new Error('Počet míst neodpovídá rozložení.');return'Řady, dvojice a U mají správnou geometrii.'}],
  ['privacy','Soukromí diagnostiky',()=>{const text=JSON.stringify(diagnosticSnapshot());const knownName=getClasses({includeArchived:true}).flatMap(item=>item.students).find(Boolean)?.displayName;if(text.includes('@')||(knownName&&text.includes(knownName)))throw new Error('Diagnostika obsahuje osobní údaj.');return'Diagnostika neobsahuje jména ani e-mailové adresy.'}],
  ['pwa','PWA a offline podpora',()=>('serviceWorker'in navigator&&document.querySelector('link[rel="manifest"]'))?'Manifest a Service Worker jsou dostupné.':Promise.reject(new Error('PWA podpora není úplná.'))],
]}
function renderProductionProgress({done=0,total=0,label='',running=false}={}){const root=$('#productionProgress'),bar=$('#productionProgressBar'),percent=$('#productionProgressPercent'),text=$('#productionProgressLabel');if(!root)return;const value=total?Math.round(done/total*100):0;root.hidden=!running&&done===0;if(bar)bar.style.width=`${value}%`;if(percent)percent.textContent=`${value} %`;if(text)text.textContent=label||(!running&&done===total&&total?'Kontrola dokončena.':'Připravuji kontrolu…');root.classList.toggle('complete',!running&&total>0&&done===total)}
function productionYield(){return new Promise(resolve=>setTimeout(resolve,45))}
async function runProductionChecks(){const definitions=productionCheckDefinitions(),checks=[];App.productionChecks={createdAt:nowIso(),checks};renderProductionChecks();renderProductionProgress({done:0,total:definitions.length,label:'Připravuji kontrolu…',running:true});for(let index=0;index<definitions.length;index++){const[id,label,fn]=definitions[index];renderProductionProgress({done:index,total:definitions.length,label:`${index+1}/${definitions.length} · ${label}`,running:true});await productionYield();checks.push(await productionCheck(id,label,fn));App.productionChecks={createdAt:App.productionChecks.createdAt,checks};renderProductionChecks();renderProductionProgress({done:index+1,total:definitions.length,label:`${index+1}/${definitions.length} · ${label}`,running:index+1<definitions.length});await productionYield()}renderProductionHealth();updateRuntimeHealth();return checks}
function renderProductionHealth(){const root=$('#productionHealth');if(!root)return;const health=storageHealthSnapshot(),invalidPrimary=health.primaryPresent&&!health.primaryValid,invalidLastGood=health.lastGoodPresent&&!health.lastGoodValid;const status=!health.available?'bad':invalidPrimary||invalidLastGood||!!App.storageError?'warn':'good';const healthMark=(present,valid)=>present?(valid?'✓':'!'):'—',issue=status==='warn'?(invalidPrimary?'Primární zápis není platný.':invalidLastGood?'Bezpečná kopie není platná.':App.storageError?.message||'Zkontrolujte lokální úložiště.'):'Všechny dostupné kontroly úložiště jsou v pořádku.';root.classList.remove('status-good','status-warn','status-bad');root.classList.add(`status-${status}`);root.innerHTML=`<div class="health-head"><div><span>STAV DATOVÉHO TREZORU</span><h3>${status==='good'?'Připraveno k provozu':status==='warn'?'Vyžaduje pozornost':'Úložiště není dostupné'}</h3></div><i class="health-dot ${status}"></i></div><div class="health-grid"><span><b>${healthMark(health.primaryPresent,health.primaryValid)}</b> Primární data</span><span><b>${healthMark(health.lastGoodPresent,health.lastGoodValid)}</b> Bezpečná kopie</span><span><b>${health.recoveryAvailable?'✓':'—'}</b> Stav před importem</span><span><b>${health.saveCount}</b> Bezpečných zápisů</span></div><small>${escapeHtml(issue)} ${health.lastSavedAt?`Poslední zápis: ${formatDateTime(health.lastSavedAt)} · ${Math.ceil(health.primaryBytes/1024)} kB`:'Data zatím nebyla uložena.'}</small>${App.recoveryState?.message?`<p class="recovery-notice">${escapeHtml(App.recoveryState.message)}</p>`:''}`;const restore=$('#restoreRecovery');if(restore)restore.disabled=!health.recoveryAvailable}
function renderProductionChecks(){const root=$('#productionCheckResults');if(!root)return;const checks=App.productionChecks?.checks||[];root.innerHTML=checks.length?checks.map(item=>`<div class="production-check ${item.state}"><i>${item.state==='pass'?'✓':'!'}</i><span><b>${escapeHtml(item.label)}</b><small>${escapeHtml(item.detail)} · ${item.durationMs} ms</small></span></div>`).join(''):'<div class="production-check pending"><i>·</i><span><b>Kontrola ještě nebyla spuštěna</b><small>Ověří data, zálohu, import, výkon, soukromí a PWA.</small></span></div>'}
function diagnosticReport(){return{...diagnosticSnapshot(),schema:'sortio-production-diagnostic-v1',storage:storageHealthSnapshot(),checks:App.productionChecks||null,environment:{language:navigator.language,platform:navigator.platform,viewport:{width:innerWidth,height:innerHeight},standalone:matchMedia('(display-mode: standalone)').matches}}}
function downloadDiagnostic(){downloadText(`SORTIO-diagnostika-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(diagnosticReport(),null,2))}
async function copyDiagnostic(){const text=JSON.stringify(diagnosticReport(),null,2);try{await navigator.clipboard.writeText(text);toast('Diagnostika byla zkopírována.','success')}catch(_){downloadText('SORTIO-diagnostika.json',text);toast('Kopírování nebylo dostupné, diagnostika byla stažena.','info')}}
function bindProductionTools(){$('#createDemoClass')?.addEventListener('click',()=>{createDemoClass();activateRoute('classes')});$('#runProductionChecks')?.addEventListener('click',async event=>{const button=event.currentTarget;button.disabled=true;button.textContent='Kontroluji…';try{await runProductionChecks()}finally{button.disabled=false;button.textContent='Spustit kontrolu'}});$('#downloadDiagnostic')?.addEventListener('click',downloadDiagnostic);$('#copyDiagnostic')?.addEventListener('click',copyDiagnostic);$('#restoreRecovery')?.addEventListener('click',()=>{try{if(App.settings.confirmDestructive!==false&&!confirm('Vrátit data do stavu před posledním importem zálohy?'))return;restoreRecoverySnapshot();toast('Předchozí stav byl obnoven.','success')}catch(error){toast(error.message,'error')}});renderProductionHealth();renderProductionChecks();renderProductionProgress({done:0,total:0})}

function sanitizeDiagnosticMessage(value=''){let text=String(value||'');for(const classItem of getClasses({includeArchived:true}))for(const student of classItem.students||[])if(student.displayName)text=text.split(student.displayName).join('[STUDENT]');return text.replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi,'[EMAIL]').slice(0,500)}
function diagnosticSnapshot(){const classes=getClasses({includeArchived:true});return{schema:'sortio-diagnostic-v5',appId:APP_ID,version:SORTIO_VERSION,createdAt:nowIso(),role:studioAccessRole(),route:App.route,online:navigator.onLine,storageAvailable:!!safeStorage(),serviceWorker:'serviceWorker'in navigator,motion:App.settings.motion,theme:App.settings.theme,moduleCount:MODULES.length,classCount:classes.length,studentCount:classes.reduce((sum,item)=>sum+classStudents(item,{includeArchived:true}).length,0),ruleCount:classes.reduce((sum,item)=>sum+item.groupRules.together.length+item.groupRules.apart.length+Object.keys(item.groupRules.pins).length,0),roleAssignmentCount:classes.reduce((sum,item)=>sum+item.roleHistory.length,0),seatingPlanCount:classes.filter(item=>item.seatingPlan.seats.length).length,engagementCount:classes.reduce((sum,item)=>sum+(item.engagementHistory?.length||0),0),scoreboardCount:classes.filter(item=>item.toolState?.scores?.length).length,lastOperation:App.lastOperation,lastError:App.lastError?{name:App.lastError.name,message:sanitizeDiagnosticMessage(App.lastError.message)}:null,storageError:App.storageError?{message:sanitizeDiagnosticMessage(App.storageError.message),createdAt:App.storageError.createdAt}:null,recovery:{recovered:!!App.recoveryState?.recovered,source:App.recoveryState?.source||null},privacy:{studentNamesStoredLocally:true,emailDataStored:false,externalDataTransfer:true,externalStudentDataTransfer:false,mediaLibraryExternalQueryOnly:true,telemetryContainsPersonalData:false,diagnosticContainsStudentNames:false}}}
window.SORTIO_DIAGNOSTICS={snapshot:diagnosticSnapshot,report:()=>typeof diagnosticReport==='function'?diagnosticReport():diagnosticSnapshot(),runChecks:()=>typeof runProductionChecks==='function'?runProductionChecks():[]};

let sortioProductionBound=false;const sortioProductionBind=bindProductionTools;
globalThis.__SORTIO_PRODUCTION_TOOLS__={bind(){if(sortioProductionBound)return;sortioProductionBound=true;sortioProductionBind()},health:renderProductionHealth,run:runProductionChecks,snapshot:diagnosticSnapshot,report:diagnosticReport};
})();
