import { chromium } from 'playwright';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { startStaticServer } from './qa-core.mjs';
const ROOT=path.join(path.dirname(fileURLToPath(import.meta.url)),'..');
const {server,baseUrl}=await startStaticServer(path.join(ROOT,'dist'),{qaAppId:'sortio'});
let executablePath=process.env.GHRAB_CHROMIUM_PATH||'';if(!executablePath){for(const candidate of [chromium.executablePath(),'/usr/bin/chromium','/usr/bin/google-chrome'])if(candidate&&existsSync(candidate)){executablePath=candidate;break}}
let browser;try{
  browser=await chromium.launch({headless:true,...(executablePath?{executablePath}:{}),args:['--no-sandbox','--disable-dev-shm-usage']});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  await page.route('**/AI-Studio-GHRAB/access/app-guard.js',route=>route.fulfill({contentType:'text/javascript',body:"export async function protectApp(appId){const permit={appId,role:'admin',apps:[appId],qa:true};document.documentElement.dataset.ghrabAccess='granted';document.dispatchEvent(new CustomEvent('ghrab:app-access-granted',{detail:{appId,permit}}));return true}"}));
  await page.route('**/AI-Studio-GHRAB/access/access-gate.css',route=>route.fulfill({contentType:'text/css',body:''}));
  await page.route('**/AI-Studio-GHRAB/config/support.json',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({administratorEmail:'balaz@ghrabuvka.cz'})}));
  await page.route('**/AI-Studio-GHRAB/config/apps.generated.json',route=>route.fulfill({status:200,contentType:'application/json',body:'[]'}));
  const errors=[];page.on('pageerror',error=>errors.push(String(error)));
  await page.goto(`${baseUrl}/index.html`);await page.waitForSelector('.sortio-stage');await page.evaluate(()=>localStorage.clear());await page.reload();await page.waitForSelector('.sortio-stage');
  await page.locator('[data-action="open-import"]').first().click();await page.fill('#importClassName','Testovací skupina');await page.fill('#isPaste','alex.novak@example.com,bara.svobodova@example.com,cyril.dlouhy@example.com,dana.mala@example.com,erik.vesely@example.com,filip.kral@example.com,gabriela.nova@example.com,hana.sykorova@example.com');await page.click('[data-action="parse-import"]');if(await page.locator('.import-preview-row').count()!==8)throw new Error('Import nerozpoznal 8 smyšlených studentů.');await page.click('[data-action="save-import"]');await page.waitForSelector('.student-row');if(await page.locator('.student-row').count()!==8)throw new Error('Třída nemá 8 studentů.');
  await page.click('[data-route="groups"]');await page.waitForSelector('#groupsWorkspace');await page.click('[data-action="group-panel"][data-panel="rules"]');
  const first=await page.locator('#ruleStudentA option').nth(1).getAttribute('value');const second=await page.locator('#ruleStudentB option').nth(2).getAttribute('value');await page.selectOption('#ruleStudentA',first);await page.selectOption('#ruleStudentB',second);await page.selectOption('#ruleType','apart');await page.click('[data-action="add-pair-rule"]');if(await page.locator('.rule-chip').count()!==1)throw new Error('Pravidlo od sebe nebylo uloženo.');
  await page.locator('[data-action="student-level"]').nth(0).selectOption('A');await page.locator('[data-action="student-level"]').nth(1).selectOption('C');await page.click('[data-action="group-panel"][data-panel="build"]');await page.click('[data-smart-mode="balanced"]');await page.click('[data-group-mode="count"]');await page.fill('#groupValue','2');await page.click('[data-action="generate-groups"]');await page.waitForSelector('.generated-group');if(await page.locator('.generated-group').count()!==2)throw new Error('Osm studentů se nerozdělilo do dvou skupin.');
  const apartSame=await page.evaluate(([a,b])=>{const cards=[...document.querySelectorAll('.generated-group')];return cards.some(card=>{const text=card.textContent;const data=JSON.parse(localStorage.getItem('sortio.data.v5'));const c=data.classes[0];const sa=c.students.find(x=>x.id===a)?.displayName;const sb=c.students.find(x=>x.id===b)?.displayName;return text.includes(sa)&&text.includes(sb)})},[first,second]);if(apartSame)throw new Error('Pravidlo od sebe bylo porušeno.');
  await page.click('[data-route="roles"]');await page.waitForSelector('#rolesWorkspace');await page.fill('#topicCatalogInput','Debata pro\nDebata proti');await page.click('[data-action="save-catalogs"]');await page.click('[data-action="assign-roles"]');await page.click('[data-action="assign-topics"]');if(await page.locator('.role-group-card').count()!==2)throw new Error('Role se nezobrazily pro obě skupiny.');if(!(await page.locator('.role-list').first().textContent())?.includes('Mluvčí'))throw new Error('Role Mluvčí nebyla přidělena.');
  await page.click('[data-route="seating"]');await page.waitForSelector('#seatingWorkspace');for(const [row,column]of [[0,0],[0,1],[1,0],[1,1]])await page.locator(`[data-seating-shape-cell][data-row="${row}"][data-column="${column}"]`).click();if((await page.locator('[data-seating-shape-cell].active').count())!==4)throw new Error('Editor tvaru učebny neoznačil 4 dvojmístné lavice.');await page.click('[data-action="apply-seating-layout"]');await page.waitForSelector('.desk-map');if(await page.locator('.desk-unit').count()!==4)throw new Error('Čtyři označené buňky nevytvořily 4 lavice.');if(await page.locator('.seat').count()!==8)throw new Error('Čtyři dvojmístné lavice nevytvořily 8 míst.');const centerDelta=await page.evaluate(()=>{const stage=document.querySelector('.seating-stage')?.getBoundingClientRect(),map=document.querySelector('.desk-map')?.getBoundingClientRect();return stage&&map?Math.abs((stage.left+stage.width/2)-(map.left+map.width/2)):999});if(centerDelta>8)throw new Error(`Vlastní tvar učebny není vycentrovaný (odchylka ${centerDelta.toFixed(1)} px).`);await page.locator('[data-action="front-preference"]').first().check();await page.click('[data-action="assign-seating"]');const occupied=await page.locator('.seat[data-student-id]').evaluateAll(nodes=>nodes.filter(node=>node.dataset.studentId).length);if(occupied!==8)throw new Error(`Zasedací pořádek obsadil ${occupied} místo 8 míst.`);await page.locator('[data-action="toggle-seat-lock"]').first().click();if(await page.locator('.seat.locked').count()!==1)throw new Error('Místo se nepodařilo uzamknout.');
  await page.click('[data-route="tools"]');await page.waitForSelector('[data-lesson-board]');const boardUi=await page.evaluate(()=>{const project=document.querySelector('[data-board-action="project-board"]'),swatches=[...document.querySelectorAll('.background-mini .background-swatch')].slice(0,6);const ps=project?getComputedStyle(project):null;return{projectVisible:!!ps&&ps.display!=='none'&&ps.visibility!=='hidden'&&Number(ps.opacity)>0&&ps.backgroundImage!=='none',swatches:swatches.map(node=>getComputedStyle(node).backgroundImage),backgroundFit:(()=>{const img=document.createElement('img');img.className='lesson-board-background-image';document.body.append(img);const value=getComputedStyle(img).objectFit;img.remove();return value})()}});if(!boardUi.projectVisible)throw new Error('Tlačítko Promítnout ve Výukovém panelu není viditelně zvýrazněné.');if(boardUi.swatches.length<6||boardUi.swatches.some(value=>!value||value==='none'))throw new Error('Miniatury barevných pozadí nejsou vykreslené.');if(boardUi.backgroundFit!=='contain')throw new Error(`Obrazové pozadí se stále ořezává (object-fit=${boardUi.backgroundFit}).`);await page.click('[data-board-add="text"]');await page.waitForSelector('.lesson-widget');await page.click('[data-board-action="board-clear"]');await page.waitForSelector('.lesson-clear-overlay');if(!(await page.locator('.lesson-clear-overlay').textContent())?.includes('Opravdu vyčistit pracovní plochu?'))throw new Error('Potvrzení vyčištění panelu není zobrazené jako vlastní dialog.');await page.click('[data-board-clear-cancel]');
  const stored=await page.evaluate(()=>localStorage.getItem('sortio.data.v5')||'');if(stored.includes('@example.com'))throw new Error('E-mailová adresa se dostala do uložených dat.');if(!stored.includes('sortio-data-v5'))throw new Error('Nový datový model nebyl uložen.');
  await page.goto(`${baseUrl}/manual/index.html`);await page.waitForSelector('.toc');await page.goto(`${baseUrl}/tests/index.html`);await page.waitForSelector('#runBtn');await page.click('#runBtn');await page.waitForFunction(()=>document.querySelector('#total')?.textContent!=='0');if(Number(await page.locator('#failed').textContent())!==0)throw new Error('Interní runtime testy hlásí selhání.');if(errors.length)throw new Error(errors.join('\n'));
  console.log('[headless] Import, skupiny, role, dvojmístné lavice, centrování zasedacího plánu, panelová UI regrese, datový model v5, manuál a produkční testy prošly.');
}finally{if(browser)await browser.close();server.close()}
