import { chromium } from 'playwright';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { startStaticServer } from './qa-core.mjs';
const ROOT=path.join(path.dirname(fileURLToPath(import.meta.url)),'..');
const {server,baseUrl}=await startStaticServer(path.join(ROOT,'dist'));
let executablePath=process.env.GHRAB_CHROMIUM_PATH||'';if(!executablePath){for(const candidate of [chromium.executablePath(),'/usr/bin/chromium','/usr/bin/google-chrome'])if(candidate&&existsSync(candidate)){executablePath=candidate;break}}
let browser;try{
  browser=await chromium.launch({headless:true,...(executablePath?{executablePath}:{}),args:['--no-sandbox','--disable-dev-shm-usage']});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  await page.route('**/AI-Studio-GHRAB/access/app-guard.js',route=>route.fulfill({contentType:'text/javascript',body:"export async function protectApp(){document.documentElement.dataset.ghrabAccess='granted';return true}"}));
  await page.route('**/AI-Studio-GHRAB/access/access-gate.css',route=>route.fulfill({contentType:'text/css',body:''}));
  const errors=[];page.on('pageerror',error=>errors.push(String(error)));
  await page.goto(`${baseUrl}/index.html`);await page.waitForSelector('.app-shell');await page.evaluate(()=>localStorage.clear());await page.reload();await page.waitForSelector('.app-shell');
  await page.locator('[data-action="open-import"]').first().click();await page.fill('#importClassName','Testovací skupina');await page.fill('#isPaste','alex.novak@example.com,bara.svobodova@example.com,cyril.dlouhy@example.com,dana.mala@example.com,erik.vesely@example.com,filip.kral@example.com,gabriela.nova@example.com,hana.sykorova@example.com');await page.click('[data-action="parse-import"]');if(await page.locator('.import-preview-row').count()!==8)throw new Error('Import nerozpoznal 8 smyšlených studentů.');await page.click('[data-action="save-import"]');await page.waitForSelector('.student-row');if(await page.locator('.student-row').count()!==8)throw new Error('Třída nemá 8 studentů.');
  await page.click('[data-route="groups"]');await page.waitForSelector('#groupsWorkspace');await page.click('[data-action="group-panel"][data-panel="rules"]');
  const first=await page.locator('#ruleStudentA option').nth(1).getAttribute('value');const second=await page.locator('#ruleStudentB option').nth(2).getAttribute('value');await page.selectOption('#ruleStudentA',first);await page.selectOption('#ruleStudentB',second);await page.selectOption('#ruleType','apart');await page.click('[data-action="add-pair-rule"]');if(await page.locator('.rule-chip').count()!==1)throw new Error('Pravidlo od sebe nebylo uloženo.');
  await page.locator('[data-action="student-level"]').nth(0).selectOption('A');await page.locator('[data-action="student-level"]').nth(1).selectOption('C');await page.click('[data-action="group-panel"][data-panel="build"]');await page.click('[data-smart-mode="balanced"]');await page.click('[data-group-mode="count"]');await page.fill('#groupValue','2');await page.click('[data-action="generate-groups"]');await page.waitForSelector('.generated-group');if(await page.locator('.generated-group').count()!==2)throw new Error('Osm studentů se nerozdělilo do dvou skupin.');
  const apartSame=await page.evaluate(([a,b])=>{const cards=[...document.querySelectorAll('.generated-group')];return cards.some(card=>{const text=card.textContent;const data=JSON.parse(localStorage.getItem('sortio.data.v5'));const c=data.classes[0];const sa=c.students.find(x=>x.id===a)?.displayName;const sb=c.students.find(x=>x.id===b)?.displayName;return text.includes(sa)&&text.includes(sb)})},[first,second]);if(apartSame)throw new Error('Pravidlo od sebe bylo porušeno.');
  await page.click('[data-route="roles"]');await page.waitForSelector('#rolesWorkspace');await page.fill('#topicCatalogInput','Debata pro\nDebata proti');await page.click('[data-action="save-catalogs"]');await page.click('[data-action="assign-roles"]');await page.click('[data-action="assign-topics"]');if(await page.locator('.role-group-card').count()!==2)throw new Error('Role se nezobrazily pro obě skupiny.');if(!(await page.locator('.role-list').first().textContent())?.includes('Mluvčí'))throw new Error('Role Mluvčí nebyla přidělena.');
  await page.click('[data-route="seating"]');await page.waitForSelector('#seatingWorkspace');await page.selectOption('#seatingTemplate','rows');await page.fill('#seatingRows','3');await page.fill('#seatingColumns','3');await page.click('[data-action="apply-seating-layout"]');if(await page.locator('.seat').count()!==9)throw new Error('Rozložení 3 × 3 nevytvořilo 9 míst.');await page.locator('[data-action="front-preference"]').first().check();await page.click('[data-action="assign-seating"]');const occupied=await page.locator('.seat select').evaluateAll(nodes=>nodes.filter(node=>node.value).length);if(occupied!==8)throw new Error(`Zasedací pořádek obsadil ${occupied} místo 8 míst.`);await page.locator('[data-action="toggle-seat-lock"]').first().click();if(await page.locator('.seat.locked').count()!==1)throw new Error('Místo se nepodařilo uzamknout.');
  const stored=await page.evaluate(()=>localStorage.getItem('sortio.data.v5')||'');if(stored.includes('@example.com'))throw new Error('E-mailová adresa se dostala do uložených dat.');if(!stored.includes('sortio-data-v5'))throw new Error('Nový datový model nebyl uložen.');
  await page.goto(`${baseUrl}/manual/index.html`);await page.waitForSelector('.toc');await page.goto(`${baseUrl}/tests/index.html`);await page.waitForSelector('#runBtn');await page.click('#runBtn');await page.waitForFunction(()=>document.querySelector('#total')?.textContent!=='0');if(Number(await page.locator('#failed').textContent())!==0)throw new Error('Interní runtime testy hlásí selhání.');if(errors.length)throw new Error(errors.join('\n'));
  console.log('[headless] Import, chytré skupiny, pravidla, role, zasedací pořádek, datový model v5, manuál a produkční testy prošly.');
}finally{if(browser)await browser.close();server.close()}
